AllCops:
  TargetRubyVersion: 2.4

Layout/AlignArguments:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/For:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/LineLength:
  Enabled: false
